### ISSUE TITLE
Add Amazon Affiliate Links

### ISSUE THREAD

**Issue by moviedatascience** [Groa-Labs/groa-ds#2]
## Description

One of the few revenue options available is affiliate links to DVD purchases. This won't really make us any money, but it could go towards covering some of the hosting costs. 

It could also help offset costs if there is an influx of traffic, since conversion rates will remain consistent. 

## Finish Line

Programmatic access to the Affiliates API, and the DB populated with affiliate links for Groa instead of the JustWatch links.

**Comment by vishnuyar** [comment]
do you have the affiliate links ready ?

**Comment by moviedatascience** [comment]
No I got denied because we weren't using the links in the site. 

I need to write a script that changes all of the justwatch referral links to groa referral links. 

I believe it's as simple as changing the end of the link. For instance here is a justwatch link:

`https://www.amazon.com/gp/product/B006S8R1CS?camp=1789&creativeASIN=B006S8R1CS&ie=UTF8&linkCode=xm2&tag=justwatch09-20`

and the groa link would be

`https://www.amazon.com/gp/product/B006S8R1CS?camp=1789&creativeASIN=B006S8R1CS&ie=UTF8&linkCode=xm2&tag=groa07-20`

**Comment by moviedatascience** [comment]
This has been completed. The SQL I ran was:

`UPDATE movie_providers
SET 
provider_movie_url = REPLACE (provider_movie_url, 'justwatch09-20', 'groa07-20');`

I guess we just need to make sure and run this whenever we are updating the provider information.
