### ISSUE TITLE
Scrape Boxoffice Mojo for Production Information

### ISSUE THREAD

**Issue by moviedatascience** [Groa-Labs/groa-ds#5]
In order to make comparisons between production studios I need to know the budget and revenue information for each movie.

**Comment by moviedatascience** [comment]
https://github.com/jacobkap/boxoffice

**Comment by moviedatascience** [comment]
https://github.com/ecole96/BoxOfficeMojoAPI/blob/master/boxofficemojo.py

**Comment by vishnuyar** [comment]
I can work on this issue.

**Comment by moviedatascience** [comment]
This has been completed and box office data is in an s3 bucket
